version: '3'

services:
  postgres-db:
    image: postgres:14
    container_name: ads_optimization_db
    environment:
      POSTGRES_DB: ads_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres-db:5432/ads_db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    depends_on:
      - postgres-db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  airflow-webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres-db:5432/ads_db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    depends_on:
      - airflow-scheduler
    ports:
      - "8090:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver

volumes:
  pgdata:
